/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cr.ac.ucr.proyectoparchis.View;

import java.awt.event.ActionListener;

/**
 *
 * @author Allan
 */
public class GUIGameOver extends javax.swing.JFrame 
    {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIGameOver.class.getName());

    /**
     * Creates new form GUIGameOver
     */
    public GUIGameOver()
    {
        initComponents();
    }
    
    public void setListener(ActionListener controller) 
    {
        this.btnBack.addActionListener(controller);
    }//fin metodo
    
    public void setTimer(String timer) 
    {
        this.ibmTimer.setText(timer+" segundos");
    }//fin metodo

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtFinalPoint = new javax.swing.JTextField();
        ibmTimer = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        jLabel2.setText("Perdiste!");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        jLabel3.setText("Puntaje Final");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 150, 30));

        jLabel4.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        jLabel4.setText("Tiempo de partida");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Back.jpg"))); // NOI18N
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 360, 50, 50));

        txtFinalPoint.setBackground(new java.awt.Color(255, 0, 0));
        txtFinalPoint.setText("jTextField1");
        getContentPane().add(txtFinalPoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 160, 160, -1));

        ibmTimer.setBackground(new java.awt.Color(255, 0, 0));
        getContentPane().add(ibmTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 100, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fondo progra 4.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIGameOver().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JTextField ibmTimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtFinalPoint;
    // End of variables declaration//GEN-END:variables
}
