/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cr.ac.ucr.proyectoparchis.View;

import cr.ac.ucr.proyectoparchis.Controller.PlayController;
import java.awt.Graphics;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Allan
 */
public class GUIPlay extends javax.swing.JFrame 
{
    PlayController playController;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIPlay.class.getName());

    /**
     * Creates new form GUIPlay
     */
    public GUIPlay(PlayController playController)
    {
        initComponents();
        this.playController = playController;
        
        panelBoard1.setController(playController);
    }//fin constructor 
    
    
    public void setListenerPlay(ActionListener controller)
    {
        this.btnBack.addActionListener(controller);
        this.btnDado.addActionListener(controller);
        addMouseListener((MouseListener) controller);
    }//fin metodo
    
    
    public void setControllerGUI(PlayController playController) 
    {
        this.playController = playController;// se usa para crear una misma instancia en diferentes clases
    }//fin metodo 
    
    public void setIbmPuntajeP1(String puntos) 
    {
        this.ibmPuntajeP1.setText(puntos+" puntos");
    }//fin metodo
    
    public void setIbmPuntaje2(String puntos)
    {
        this.ibmPuntaje2.setText(puntos+" puntos");
    }//fin metodo
    
    public void setIbmTiempo(String tiempo) 
    {
        this.ibmTiempo.setText(tiempo+" segundos");
    }//fin metodo
    
    @Override
    public void repaint() 
    {
        jblPanel.repaint();
    }//fin metodo

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnDado = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ibmPuntajeP1 = new javax.swing.JLabel();
        ibmTiempo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ibmPuntaje2 = new javax.swing.JLabel();
        jblFondo = new javax.swing.JLabel();
        panelBoard1 = new cr.ac.ucr.proyectoparchis.View.panelBoard();
        jblPanel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Dado.png"))); // NOI18N
        btnDado.setActionCommand("Lanzar dado");
        getContentPane().add(btnDado, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 520, 50, 50));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Back.jpg"))); // NOI18N
        btnBack.setActionCommand("Back");
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 520, 50, 50));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Puntaje Jugador 1");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 140, -1));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Tiempo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, 70, -1));

        ibmPuntajeP1.setBackground(new java.awt.Color(204, 204, 204));
        ibmPuntajeP1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        ibmPuntajeP1.setOpaque(true);
        getContentPane().add(ibmPuntajeP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, 130, 20));
        getContentPane().add(ibmTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, 90, 20));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Puntaje jugador 2");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 150, -1));

        ibmPuntaje2.setBackground(new java.awt.Color(204, 204, 204));
        ibmPuntaje2.setOpaque(true);
        getContentPane().add(ibmPuntaje2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, 130, 20));

        jblFondo.setBackground(new java.awt.Color(255, 255, 204));
        jblFondo.setForeground(new java.awt.Color(255, 204, 204));
        jblFondo.setOpaque(true);
        getContentPane().add(jblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 250, 590));

        panelBoard1.setOpaque(false);

        javax.swing.GroupLayout panelBoard1Layout = new javax.swing.GroupLayout(panelBoard1);
        panelBoard1.setLayout(panelBoard1Layout);
        panelBoard1Layout.setHorizontalGroup(
            panelBoard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        panelBoard1Layout.setVerticalGroup(
            panelBoard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        getContentPane().add(panelBoard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 590));

        jblPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tablero 6.png"))); // NOI18N
        getContentPane().add(jblPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDado;
    private javax.swing.JLabel ibmPuntaje2;
    private javax.swing.JLabel ibmPuntajeP1;
    private javax.swing.JLabel ibmTiempo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jblFondo;
    private javax.swing.JLabel jblPanel;
    private cr.ac.ucr.proyectoparchis.View.panelBoard panelBoard1;
    // End of variables declaration//GEN-END:variables
}
