/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cr.ac.ucr.proyectoparchis.View;

/**
 *
 * @author Allan
 */
public class GUIStartGame extends javax.swing.JFrame 
{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIStartGame.class.getName());

    /**
     * Creates new form GUIStartGame
     */
    public GUIStartGame()
    {
        initComponents();
    }
    
    public PanelData getPanelData() 
    {
        return this.panelData1;
    }//fin metodo instanciador
    
    public PanelButtons getPanelButtons() 
    {
        return this.panelButtons1;
    }//fin metodo instanciador
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jButton1 = new javax.swing.JButton();
        panelButtons1 = new cr.ac.ucr.proyectoparchis.View.PanelButtons();
        panelData1 = new cr.ac.ucr.proyectoparchis.View.PanelData();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(panelButtons1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));
        getContentPane().add(panelData1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    
    
    
            

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private cr.ac.ucr.proyectoparchis.View.PanelButtons panelButtons1;
    private cr.ac.ucr.proyectoparchis.View.PanelData panelData1;
    // End of variables declaration//GEN-END:variables
}
