/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cr.ac.ucr.proyectoparchis.View;

import java.awt.event.ActionListener;



/**
 *
 * @author Allan
 */
public class GUIWin extends javax.swing.JFrame
{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIWin.class.getName());

    /**
     * Creates new form GUIWin
     */
    public GUIWin()
    {
        initComponents();
    }
    
    public void setListener(ActionListener controller)
    {
        this.btnBack.addActionListener(controller);
    }//fin metodo setListerner
    
    public void setTimer(String timer) 
    {
        this.ibmTimer.setText(timer+" segundos");
    }//fin Timer

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtStadistics = new javax.swing.JTextField();
        ibmTimer = new javax.swing.JTextField();
        txt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        jLabel2.setText("Felicidades!  ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 230, 60));

        jLabel3.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        jLabel3.setText("Lograste conquistar la cima!!");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 530, 60));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Back.jpg"))); // NOI18N
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 50, 50));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Estadisticas Finales");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Tiempo de partida: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, 30));

        txtStadistics.setBackground(new java.awt.Color(255, 204, 204));
        txtStadistics.setText("jTextField1");
        getContentPane().add(txtStadistics, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 210, -1));

        ibmTimer.setBackground(new java.awt.Color(255, 204, 204));
        ibmTimer.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ibmTimerActionPerformed(evt);
            }
        });
        getContentPane().add(ibmTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 390, 140, 30));

        txt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fondo progra 4.jpg"))); // NOI18N
        getContentPane().add(txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ibmTimerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ibmTimerActionPerformed
    {//GEN-HEADEREND:event_ibmTimerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ibmTimerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIWin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JTextField ibmTimer;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel txt;
    private javax.swing.JTextField txtStadistics;
    // End of variables declaration//GEN-END:variables
}
