/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cr.ac.ucr.proyectoparchis.View;

import cr.ac.ucr.proyectoparchis.Controller.PlayController;
import java.awt.Graphics;

/**
 *
 * @author Allan
 */
public class panelBoard extends javax.swing.JPanel 
{
    PlayController playController;

    /**
     * Creates new form panelBoard
     */
    public panelBoard()
    {
        initComponents();
    }

    public panelBoard(PlayController playController)
    {
        this.playController = playController;
    }
    
    public void setController(PlayController playController) 
    {
       this.playController = playController;// se usa para crear una misma instancia en diferentes clases
    }//fin metodo 
    
    @Override
    public void paintComponent(Graphics g) // metodo encargado de pintar las figuras
    {
        super.paintComponent(g);
        
        if(playController != null) 
        {
            playController.draw(this, g);
        }//fin if
    }//fin metodo
    
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
